services:
    menu_writer:
        class:        Hackhouse\DynamicMenuBundle\Extensions\MenuWriterExtension
        arguments:    [%menus%]
        calls:        [[ setContainer, [ @service_container ] ]]
        tags:
          -  { name: twig.extension }