<?php

namespace Hackhouse\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivationTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationTokenRepository extends EntityRepository
{
}